/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author Patil
 */
public class CreateJPanel extends javax.swing.JPanel {
    Person person;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Person p) {
        person = p;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PLanguage = new javax.swing.JLabel();
        preferredLanguage = new javax.swing.JTextField();
        City = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        BtnCreate = new javax.swing.JButton();
        State = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        FName = new javax.swing.JLabel();
        ZIP = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        zip = new javax.swing.JTextField();
        LName = new javax.swing.JLabel();
        TNum = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        telephoneNumber = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        FNum = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        faxNumber = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        DOB = new javax.swing.JLabel();
        dateofBirth = new javax.swing.JTextField();
        driverLicenseNumber = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        DLNumber = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        driverLicenseState = new javax.swing.JTextField();
        Occupation = new javax.swing.JLabel();
        DLState = new javax.swing.JLabel();
        occupation = new javax.swing.JTextField();
        socialSecurityNumber = new javax.swing.JTextField();
        MStatus = new javax.swing.JLabel();
        SSN = new javax.swing.JLabel();
        martalStatus = new javax.swing.JTextField();
        Address1 = new javax.swing.JLabel();
        Nationality = new javax.swing.JLabel();
        addressLine1 = new javax.swing.JTextField();
        nationality = new javax.swing.JTextField();
        Address2 = new javax.swing.JLabel();
        addressLine2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        PLanguage.setText("Preferred Language");

        City.setText("City");

        BtnCreate.setText("Create");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        State.setText("State");

        FName.setText("First Name");

        ZIP.setText("ZIP");

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        LName.setText("Last Name");

        TNum.setText("Telephone Number");

        Email.setText("Email");

        FNum.setText("Fax Number");

        Phone.setText("Phone");

        DOB.setText("Date of Birth");

        Gender.setText("Gender");

        DLNumber.setText("Driver's License Number");

        Occupation.setText("Occupation");

        DLState.setText("Driver's License State");

        MStatus.setText("Martial Status");

        SSN.setText("Social Security Number");

        Address1.setText("Address Line 1");

        Nationality.setText("Nationality");

        Address2.setText("Address Line 2");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("CREATE PROFILE");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(330, 330, 330)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SSN)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Phone)
                                        .addComponent(DLNumber)
                                        .addComponent(DLState))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(driverLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(socialSecurityNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                                .addComponent(driverLicenseState, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(addressLine1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                .addComponent(Address1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LName)
                                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(79, 79, 79)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Address2)
                                        .addComponent(City)
                                        .addComponent(State)
                                        .addComponent(ZIP)
                                        .addComponent(TNum)
                                        .addComponent(FNum))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(faxNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                        .addComponent(telephoneNumber)
                                        .addComponent(zip)
                                        .addComponent(state)
                                        .addComponent(city)
                                        .addComponent(addressLine2))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Nationality)
                                                .addComponent(MStatus)
                                                .addComponent(Occupation)
                                                .addComponent(Gender)
                                                .addComponent(DOB))
                                            .addGap(82, 82, 82))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(PLanguage)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(preferredLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(BtnCreate)
                                            .addGap(27, 27, 27))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nationality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(gender, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dateofBirth, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(occupation, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(martalStatus, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                    .addContainerGap(361, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FName)
                                .addComponent(firstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LName)
                                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DOB)
                                .addComponent(dateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Gender)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Email)
                                .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Phone)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Occupation)
                                .addComponent(occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MStatus)
                                .addComponent(martalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(driverLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DLNumber)
                        .addComponent(Nationality)
                        .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(driverLicenseState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DLState)
                        .addComponent(PLanguage)
                        .addComponent(preferredLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SSN)
                        .addComponent(socialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Address1)
                        .addComponent(addressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnCreate))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Address2)
                        .addComponent(addressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(City)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(State)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ZIP)
                        .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TNum)
                        .addComponent(telephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FNum)
                        .addComponent(faxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        // TODO add your handling code here:
        String firstNameInput = firstName.getText();  
        String lastNameInput = lastName.getText();    
        String emailInput = email.getText();          
        String phoneInput = phone.getText();          
        String driversLicenseNumberInput = driverLicenseNumber.getText();  
        String driversLicenseStateInput = driverLicenseState.getText();    
        String socialSecurityNumberInput = socialSecurityNumber.getText();  
        String addressLine1Input = addressLine1.getText();   
        String addressLine2Input = addressLine2.getText();   
        String cityInput = city.getText();   
        String stateInput = state.getText();   
        String zipInput = zip.getText();   
        String telephoneNumberInput = telephoneNumber.getText();   
        String faxNumberInput = faxNumber.getText();   
        String dateOfBirthInput = dateofBirth.getText();   
        String genderInput = gender.getText();   
        String occupationInput = occupation.getText();   
        String maritalStatusInput = martalStatus.getText();   
        String nationalityInput = nationality.getText();   
        String preferredLanguageInput = preferredLanguage.getText(); 
        
        person.setFirstName(firstNameInput);
        person.setLastName(lastNameInput);
        person.setEmail(emailInput);
        person.setPhone(phoneInput);
        person.setDriverLicenseNumber(driversLicenseNumberInput);
        person.setDriverLicenseState(driversLicenseStateInput);
        person.setSocialSecurityNumber(socialSecurityNumberInput);
        person.setAddressLine1(addressLine1Input);
        person.setAddressLine2(addressLine2Input);
        person.setCity(cityInput);
        person.setState(stateInput);
        person.setZip(zipInput);
        person.setTelephoneNumber(telephoneNumberInput);
        person.setFaxNumber(faxNumberInput);
        person.setDateofBirth(dateOfBirthInput);
        person.setGender(genderInput);
        person.setOccupation(occupationInput);
        person.setMartalStatus(maritalStatusInput);
        person.setNationality(nationalityInput);
        person.setPreferredLanguage(preferredLanguageInput);        
        
        JOptionPane.showMessageDialog(this, "Profile Created", "Success", JOptionPane.PLAIN_MESSAGE);
        
        firstName.setText("");
        lastName.setText("");
        email.setText("");
        phone.setText("");
        driverLicenseNumber.setText("");
        driverLicenseState.setText("");
        socialSecurityNumber.setText("");
        addressLine1.setText("");
        addressLine2.setText("");
        city.setText("");
        state.setText("");
        zip.setText("");
        telephoneNumber.setText("");
        faxNumber.setText("");
        dateofBirth.setText("");
        gender.setText("");  // Resets JComboBox to the first item
        occupation.setText("");
        martalStatus.setText("");
        nationality.setText("");
        preferredLanguage.setText("");

    }//GEN-LAST:event_BtnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JButton BtnCreate;
    private javax.swing.JLabel City;
    private javax.swing.JLabel DLNumber;
    private javax.swing.JLabel DLState;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FName;
    private javax.swing.JLabel FNum;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel LName;
    private javax.swing.JLabel MStatus;
    private javax.swing.JLabel Nationality;
    private javax.swing.JLabel Occupation;
    private javax.swing.JLabel PLanguage;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel SSN;
    private javax.swing.JLabel State;
    private javax.swing.JLabel TNum;
    private javax.swing.JLabel ZIP;
    private javax.swing.JTextField addressLine1;
    private javax.swing.JTextField addressLine2;
    private javax.swing.JTextField city;
    private javax.swing.JTextField dateofBirth;
    private javax.swing.JTextField driverLicenseNumber;
    private javax.swing.JTextField driverLicenseState;
    private javax.swing.JTextField email;
    private javax.swing.JTextField faxNumber;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField martalStatus;
    private javax.swing.JTextField nationality;
    private javax.swing.JTextField occupation;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField preferredLanguage;
    private javax.swing.JTextField socialSecurityNumber;
    private javax.swing.JTextField state;
    private javax.swing.JTextField telephoneNumber;
    private javax.swing.JTextField zip;
    // End of variables declaration//GEN-END:variables
}
