/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AccountManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.person;
import model.personhistory;

/**
 *
 * @author Patil
 */
public class ViewPersonJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    personhistory Personhistory;
    person Person;
    

    /**
     * Creates new form ViewPersonJPanel
     */
    public ViewPersonJPanel(JPanel container, personhistory history, person Person) {
        initComponents();
        userProcessContainer = container;
        Personhistory = history;
        this.Person = Person;
        refreshTextFields();
        setViewMode();
        setEditMode();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtWcity = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtWstate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtWzip = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtWphone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtHstreet = new javax.swing.JTextField();
        txtWstreet = new javax.swing.JTextField();
        txtHunit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHcity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtHstate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHzip = new javax.swing.JTextField();
        txtHphone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtWunit = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel13.setText("State");

        jLabel2.setText("Last Name");

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });

        txtWstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWstateActionPerformed(evt);
            }
        });

        jLabel3.setText("SSN");

        jLabel14.setText("Zip code");

        jLabel15.setText("Phone Number");

        jLabel4.setText("Age");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("Work Address");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Home Address");

        jLabel17.setText("Street address");

        jLabel6.setText("Street address");

        txtWphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWphoneActionPerformed(evt);
            }
        });

        jLabel7.setText("Unit Number");

        jLabel18.setText("Unit Number");

        jLabel8.setText("City");

        jLabel9.setText("State");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtHstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHstateActionPerformed(evt);
            }
        });

        jLabel10.setText("Zip code");

        jLabel11.setText("Phone Number");

        txtHphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHphoneActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel12.setText("City");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Back to Home");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFname, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(txtLname)
                    .addComponent(txtSSN)
                    .addComponent(txtAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtWstreet)
                            .addComponent(txtWcity)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(txtWzip, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel13)
                            .addComponent(txtWunit)
                            .addComponent(txtWstate)
                            .addComponent(txtWphone, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHstreet, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtHcity)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)))
                            .addComponent(txtHzip))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(txtHunit, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(txtHstate)
                            .addComponent(txtHphone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(441, 441, 441))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnUpdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHcity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtHzip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(txtHunit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHstate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtHphone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtWstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWcity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtWzip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(txtWunit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWstate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtWphone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtWstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWstateActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtWphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWphoneActionPerformed

    private void txtHstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHstateActionPerformed

    private void txtHphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHphoneActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        short age;
        String firstName = txtFname.getText();
        String lastName = txtLname.getText();
        String ssn = txtSSN.getText();
        String hStreet = txtHstreet.getText();
        String hUnit = txtHunit.getText();
        String hCity = txtHcity.getText();
        String hState = txtHstate.getText();
        int hZip;
        long hPhone;
        String wStreet = txtWstreet.getText();
        String wUnit = txtWunit.getText();
        String wCity = txtWcity.getText();
        String wState = txtWstate.getText();
        int wZip;
        long wPhone;

            if (firstName.isBlank() || lastName.isBlank() || ssn.isBlank() || hStreet.isBlank() || hUnit.isBlank() || 
                hCity.isBlank() || hState.isBlank() || wStreet.isBlank() || wUnit.isBlank() || wCity.isBlank() || wState.isBlank()) 
            {
                JOptionPane.showMessageDialog(this, "All fields are Mandatory", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                age = Short.parseShort(txtAge.getText());
                hZip = Integer.parseInt(txtHzip.getText());
                hPhone = Long.parseLong(txtHphone.getText());
                wZip = Integer.parseInt(txtWzip.getText());
                wPhone = Long.parseLong(txtWphone.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid format for Age, Zip, or Phone fields", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

Person.setFirstName(firstName);
Person.setLastName(lastName);
Person.setAge(age);
Person.setSsn(ssn);
Person.setHAddress(hStreet);
Person.setHUnitNo(hUnit);
Person.setHCity(hCity);
Person.setHState(hState);
Person.setHZip(hZip);
Person.setHPhno(hPhone);
Person.setWAddress(wStreet);
Person.setWUnitNo(wUnit);
Person.setWCity(wCity);
Person.setWState(wState);
Person.setWZip(wZip);
Person.setWPhno(wPhone);

JOptionPane.showMessageDialog(null, "Person details successfully updated", "Success", JOptionPane.INFORMATION_MESSAGE);
setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ListPersonJPanel listPersonJPanel = (ListPersonJPanel) lastPanel;
        listPersonJPanel.populateTable();
        
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtHcity;
    private javax.swing.JTextField txtHphone;
    private javax.swing.JTextField txtHstate;
    private javax.swing.JTextField txtHstreet;
    private javax.swing.JTextField txtHunit;
    private javax.swing.JTextField txtHzip;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWcity;
    private javax.swing.JTextField txtWphone;
    private javax.swing.JTextField txtWstate;
    private javax.swing.JTextField txtWstreet;
    private javax.swing.JTextField txtWunit;
    private javax.swing.JTextField txtWzip;
    // End of variables declaration//GEN-END:variables

    private void setViewMode() {
        txtAge.setEnabled(false);
        txtFname.setEnabled(false);
        txtHcity.setEnabled(false);
        txtHphone.setEnabled(false);
        txtHstate.setEnabled(false);
        txtHstreet.setEnabled(false);
        txtHunit.setEnabled(false);
        txtHzip.setEnabled(false);
        txtLname.setEnabled(false);
        txtSSN.setEnabled(false);
        txtWcity.setEnabled(false);
        txtWphone.setEnabled(false);
        txtWstate.setEnabled(false);
        txtWstreet.setEnabled(false);
        txtWunit.setEnabled(false);
        txtWzip.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
       

    }

    private void refreshTextFields() {
        txtFname.setText(Person.getFirstName());
        txtAge.setText(String.valueOf(Person.getAge())); // Assuming getAge() returns an int or similar
        txtHcity.setText(Person.getHCity());
        txtHphone.setText(Long.toString(Person.getHPhno()));
        txtHstate.setText(Person.getHState());
        txtHstreet.setText(Person.getHAddress());
        txtHunit.setText(Person.getHUnitNo());
        txtHzip.setText(Integer.toString(Person.getHZip()));
        txtLname.setText(Person.getLastName());
        txtSSN.setText(Person.getSsn());
        txtWcity.setText(Person.getWCity());
        txtWphone.setText(Long.toString(Person.getWPhno()));
        txtWstate.setText(Person.getWState());
        txtWstreet.setText(Person.getWAddress());
        txtWunit.setText(Person.getWUnitNo());
        txtWzip.setText(Integer.toString(Person.getWZip()));
    }
    
    private void setEditMode(){
        txtAge.setEnabled(true);
        txtFname.setEnabled(true);
        txtHcity.setEnabled(true);
        txtHphone.setEnabled(true);
        txtHstate.setEnabled(true);
        txtHstreet.setEnabled(true);
        txtHunit.setEnabled(true);
        txtHzip.setEnabled(true);
        txtLname.setEnabled(true);
        txtSSN.setEnabled(true);
        txtWcity.setEnabled(true);
        txtWphone.setEnabled(true);
        txtWstate.setEnabled(true);
        txtWstreet.setEnabled(true);
        txtWunit.setEnabled(true);
        txtWzip.setEnabled(true);

        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        
    }
}
