/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JPanel;
import model.person;
import model.personhistory;
import ui.AccountManager.AddPersonJPanel;
import ui.AccountManager.ListPersonJPanel;

/**
 *
 * @author patil
 */
public class MainJFrame extends javax.swing.JFrame {
    private personhistory Personhistory;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.Personhistory = new personhistory();
        generateDemoPersonData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        btnList = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnList.setText("List person");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        jButton3.setText("Search Person");

        jLabel1.setText("Person Profile");

        btnAdd.setText("Add person");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ControlPanelLayout.createSequentialGroup()
                        .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(btnList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnList)
                .addGap(49, 49, 49)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(ControlPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        AddPersonJPanel addPanel = new AddPersonJPanel(userProcessContainer,Personhistory);
        splitPane.setRightComponent(addPanel);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        ListPersonJPanel listPanel = new ListPersonJPanel(userProcessContainer,Personhistory);
        splitPane.setRightComponent(listPanel);
    }//GEN-LAST:event_btnListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnList;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

private void generateDemoPersonData() {
    // Sample 1
person firstPerson = Personhistory.addPerson();
firstPerson.setFirstName("John");
firstPerson.setLastName("Paul");
firstPerson.setSsn("854-12-6789");
firstPerson.setAge((short) 23); // short type for age
firstPerson.setHAddress("33 Lancaster Ter");
firstPerson.setHUnitNo("305");
firstPerson.setHCity("Brookline");
firstPerson.setHState("MA");
firstPerson.setHZip(02446); // int type for ZIP code
firstPerson.setHPhno(8197614428L); // long type for home phone

firstPerson.setWAddress("33 Beacon St");
firstPerson.setWUnitNo("521");
firstPerson.setWCity("Boston");
firstPerson.setWState("MA");
firstPerson.setWZip(02447); // int type for ZIP code
firstPerson.setWPhno(6174178901L); // long type for work phone

person secondPerson = Personhistory.addPerson();
secondPerson.setFirstName("Michael");
secondPerson.setLastName("Johnson");
secondPerson.setSsn("456-78-9123");
secondPerson.setAge((short) 40);
secondPerson.setHAddress("101 Cedar Street");
secondPerson.setHUnitNo("2A");
secondPerson.setHCity("Chicago");
secondPerson.setHState("IL");
secondPerson.setHZip(60601);
secondPerson.setHPhno(3125551010L);

secondPerson.setWAddress("202 Birch Lane");
secondPerson.setWUnitNo("Office 4");
secondPerson.setWCity("Chicago");
secondPerson.setWState("IL");
secondPerson.setWZip(60602);
secondPerson.setWPhno(3125552020L);

person thirdPerson = Personhistory.addPerson();
thirdPerson.setFirstName("Sophia");
thirdPerson.setLastName("Davis");
thirdPerson.setSsn("321-54-9876");
thirdPerson.setAge((short) 28);
thirdPerson.setHAddress("222 Willow Drive");
thirdPerson.setHUnitNo("1D");
thirdPerson.setHCity("Austin");
thirdPerson.setHState("TX");
thirdPerson.setHZip(73301);
thirdPerson.setHPhno(5125552222L);

thirdPerson.setWAddress("555 Cypress Road");
thirdPerson.setWUnitNo("Suite 3");
thirdPerson.setWCity("Austin");
thirdPerson.setWState("TX");
thirdPerson.setWZip(73302);
thirdPerson.setWPhno(5125553333L);

// Sample 4
person fourthPerson = Personhistory.addPerson();
fourthPerson.setFirstName("James");
fourthPerson.setLastName("Williams");
fourthPerson.setSsn("654-32-1987");
fourthPerson.setAge((short) 35);
fourthPerson.setHAddress("333 Maple Street");
fourthPerson.setHUnitNo("3B");
fourthPerson.setHCity("Miami");
fourthPerson.setHState("FL");
fourthPerson.setHZip(33101);
fourthPerson.setHPhno(3055553333L);

fourthPerson.setWAddress("666 Palm Drive");
fourthPerson.setWUnitNo("Suite 6");
fourthPerson.setWCity("Miami");
fourthPerson.setWState("FL");
fourthPerson.setWZip(33102);
fourthPerson.setWPhno(3055556666L);

// Sample 5
person fifthPerson = Personhistory.addPerson();
fifthPerson.setFirstName("Olivia");
fifthPerson.setLastName("Martinez");
fifthPerson.setSsn("789-21-3456");
fifthPerson.setAge((short) 42);
fifthPerson.setHAddress("444 Sycamore Lane");
fifthPerson.setHUnitNo("7E");
fifthPerson.setHCity("Seattle");
fifthPerson.setHState("WA");
fifthPerson.setHZip(98101);
fifthPerson.setHPhno(2065554444L);

fifthPerson.setWAddress("888 Fir Avenue");
fifthPerson.setWUnitNo("Office 12");
fifthPerson.setWCity("Seattle");
fifthPerson.setWState("WA");
fifthPerson.setWZip(98102);
fifthPerson.setWPhno(2065558888L);

    }
}

