package ui.AccountManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import javax.swing.JPanel;
import model.person;
import model.personhistory;


/**
 *
 * @author Patil
 */
public class ViewPersonJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    personhistory Personhistory;
    person Person;
    /**
     * Creates new form ViewPersonJPanel
     */
    public ViewPersonJPanel(JPanel container, personhistory history, person Person) {
        initComponents();
        userProcessContainer = container;
        Personhistory = history;
        this.Person = Person;
      //  refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWstreet = new javax.swing.JTextField();
        txtHunit = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLastName = new javax.swing.JLabel();
        lblCityH = new javax.swing.JLabel();
        txtWcity = new javax.swing.JTextField();
        lblStateH = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtWstate = new javax.swing.JTextField();
        lblZipW = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblPhoneW = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblWTitle = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtHcity = new javax.swing.JTextField();
        txtWzip = new javax.swing.JTextField();
        txtHstate = new javax.swing.JTextField();
        lblHTitle = new javax.swing.JLabel();
        lblZipH = new javax.swing.JLabel();
        lblStreetW = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblStreetH = new javax.swing.JLabel();
        txtHzip = new javax.swing.JTextField();
        txtWphone = new javax.swing.JTextField();
        txtHphone = new javax.swing.JTextField();
        lblUnitH = new javax.swing.JLabel();
        txtWunit = new javax.swing.JTextField();
        lblUnitW = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtHstreet = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        brnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        lblState.setText("State");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblLastName.setText("Last Name");

        lblCityH.setText("City");

        lblStateH.setText("State");

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });

        lblSSN.setText("SSN");

        txtWstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWstateActionPerformed(evt);
            }
        });

        lblZipW.setText("Zip code");

        lblPhoneW.setText("Phone Number");

        lblAge.setText("Age");

        lblWTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblWTitle.setText("Work Address");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtHstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHstateActionPerformed(evt);
            }
        });

        lblHTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblHTitle.setText("Home Address");

        lblZipH.setText("Zip code");

        lblStreetW.setText("Street address");

        lblPhone.setText("Phone Number");

        lblStreetH.setText("Street address");

        txtWphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWphoneActionPerformed(evt);
            }
        });

        txtHphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHphoneActionPerformed(evt);
            }
        });

        lblUnitH.setText("Unit Number");

        lblUnitW.setText("Unit Number");

        lblFirstName.setText("First Name");

        lblCity.setText("City");

        brnSave.setText("Save");

        btnUpdate.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFname, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txtLname)
                            .addComponent(txtSSN)
                            .addComponent(txtAge)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHstreet, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtHcity)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStreetH)
                                    .addComponent(lblCityH)
                                    .addComponent(lblZipH)))
                            .addComponent(txtHzip))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPhone)
                            .addComponent(lblUnitH)
                            .addComponent(lblStateH)
                            .addComponent(txtHunit, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(txtHstate)
                            .addComponent(txtHphone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtWstreet)
                            .addComponent(txtWcity)
                            .addComponent(lblStreetW)
                            .addComponent(lblCity)
                            .addComponent(lblZipW)
                            .addComponent(txtWzip, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPhoneW)
                            .addComponent(lblUnitW)
                            .addComponent(lblState)
                            .addComponent(txtWunit)
                            .addComponent(txtWstate)
                            .addComponent(txtWphone, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(brnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btnUpdate)
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblHTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblStreetH)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCityH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHcity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblZipH)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtHzip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUnitH)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(txtHunit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblStateH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHstate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPhone)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtHphone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblWTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblStreetW)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtWstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWcity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblZipW)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtWzip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUnitW)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(txtWunit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblState)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWstate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPhoneW)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtWphone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 172, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnSave)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtWstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWstateActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtHstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHstateActionPerformed

    private void txtWphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWphoneActionPerformed

    private void txtHphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHphoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCityH;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHTitle;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneW;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStateH;
    private javax.swing.JLabel lblStreetH;
    private javax.swing.JLabel lblStreetW;
    private javax.swing.JLabel lblUnitH;
    private javax.swing.JLabel lblUnitW;
    private javax.swing.JLabel lblWTitle;
    private javax.swing.JLabel lblZipH;
    private javax.swing.JLabel lblZipW;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtHcity;
    private javax.swing.JTextField txtHphone;
    private javax.swing.JTextField txtHstate;
    private javax.swing.JTextField txtHstreet;
    private javax.swing.JTextField txtHunit;
    private javax.swing.JTextField txtHzip;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWcity;
    private javax.swing.JTextField txtWphone;
    private javax.swing.JTextField txtWstate;
    private javax.swing.JTextField txtWstreet;
    private javax.swing.JTextField txtWunit;
    private javax.swing.JTextField txtWzip;
    // End of variables declaration//GEN-END:variables

    private void setViewMode() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void refreshTextFields() {
       txtFname.setText(Person.getFirstName());
        txtAge.setText(String.valueOf(Person.getAge())); // Assuming getAge() returns an int or similar
        txtHcity.setText(Person.getHCity());
        txtHphone.setText(Long.toString(Person.getHPhno()));
        txtHstate.setText(Person.getHState());
        txtHstreet.setText(Person.getHAddress());
        txtHunit.setText(Person.getHUnitNo());
        txtHzip.setText(Integer.toString(Person.getHZip()));
        txtLname.setText(Person.getLastName());
        txtSSN.setText(Person.getSsn());
        txtWcity.setText(Person.getWCity());
        txtWphone.setText(Long.toString(Person.getWPhno()));
        txtWstate.setText(Person.getWState());
        txtWstreet.setText(Person.getWAddress());
        txtWunit.setText(Person.getWUnitNo());
        txtWzip.setText(Integer.toString(Person.getWZip()));
    }
}

